"use strict";

/* ---------- Analysis page ----------
 * Shows the existing Claude AI-rating pass across all 425 guidelines (from
 * analysis.json, generated by the private data repo's generate_analysis_json.py -
 * same pattern as data.json). Once a submission backend exists, human responses
 * collected "up to that point" can be merged into the same aggregation functions
 * below without changing their shape - they already take a plain array of
 * { source, bpmNative, relevance, scope, generic, lifecycle } records.
 */

const ANALYSIS_SOURCE_ORDER = ["aws", "azure", "gcp", "gsf", "w3c", "gbpp", "ppatterns", "lean"];
const SOURCE_SHORT_LABELS = {
  aws: "AWS", azure: "Azure", gcp: "GCP", gsf: "GSF", w3c: "W3C",
  gbpp: "GBPP", ppatterns: "ppatterns.app", lean: "Lean",
};

function isDarkMode() {
  return window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
}

// Chart colors. Every chart draws from the same green family as the site's own
// --accent (the envite brand color) rather than an unrelated categorical palette,
// so the analysis page reads as one system with the rest of the site. Two-way
// splits (native/general, generic/specific) use a strong vs. muted step of that
// same green rather than a second hue - each chart's legend/labels carry the
// identity, so a shared hue doesn't cost distinguishability.
function chartPalette() {
  const dark = isDarkMode();
  return {
    ink: dark ? "#ffffff" : "#0b0b0b",
    inkSecondary: dark ? "#c3c2b7" : "#52514e",
    grid: dark ? "#2c2c2a" : "#e1e0d9",
    axis: dark ? "#383835" : "#c3c2b7",
    tooltipBg: dark ? "#eef0ee" : "#1f1f1f",
    tooltipText: dark ? "#0f1b16" : "#ffffff",
    single: dark ? "#6ccbb2" : "#1e7a5c", // reuses the site's own --accent
    strong: dark ? "#6ccbb2" : "#1e7a5c", // same accent - the "highlighted" side of a 2-way split
    muted: dark ? "#317e6d" : "#a8d9cb", // a lighter/dimmer step of the same green - the baseline side
    relevanceSteps: dark
      ? ["#173a33", "#1f5148", "#317e6d", "#6ccbb2"] // low relevance recedes toward the dark surface
      : ["#d7ede7", "#a8d9cb", "#5fb59b", "#1e7a5c"], // low relevance stays pale on the light surface
  };
}

function baseScaleOptions(pal) {
  return {
    grid: { color: pal.grid, drawTicks: false },
    ticks: { color: pal.inkSecondary, font: { size: 11.5 } },
    border: { color: pal.axis },
  };
}

function baseTooltip(pal) {
  return { backgroundColor: pal.tooltipBg, titleColor: pal.tooltipText, bodyColor: pal.tooltipText, padding: 8, cornerRadius: 6 };
}

function mountChart(canvasId, config) {
  return new Chart(document.getElementById(canvasId), config);
}

/* ---- Aggregations (mirrors analysis.ipynb's pandas groupbys) ---- */

function ratedRecords(records) {
  return records.filter((r) => r.relevance !== null && r.relevance !== undefined);
}

function countsPerSource(records) {
  const counts = Object.fromEntries(ANALYSIS_SOURCE_ORDER.map((s) => [s, 0]));
  records.forEach((r) => { counts[r.source] = (counts[r.source] || 0) + 1; });
  return ANALYSIS_SOURCE_ORDER.map((s) => counts[s]);
}

function relevanceDistribution(records) {
  const counts = [0, 0, 0, 0];
  ratedRecords(records).forEach((r) => { counts[r.relevance] += 1; });
  return counts;
}

function highRelevanceShareBySource(records) {
  return ANALYSIS_SOURCE_ORDER.map((source) => {
    const inSource = ratedRecords(records.filter((r) => r.source === source));
    const high = inSource.filter((r) => r.relevance >= 3).length;
    return inSource.length ? (high / inSource.length) * 100 : 0;
  });
}

function relevanceDistributionPerSource(records) {
  // Returns one array per relevance value 0..3, each holding one % per source (stacked-to-100 layout).
  const perRelevance = [[], [], [], []];
  ANALYSIS_SOURCE_ORDER.forEach((source) => {
    const inSource = ratedRecords(records.filter((r) => r.source === source));
    const total = inSource.length || 1;
    for (let rel = 0; rel <= 3; rel++) {
      perRelevance[rel].push((inSource.filter((r) => r.relevance === rel).length / total) * 100);
    }
  });
  return perRelevance;
}

function scopeCounts(records) {
  const counts = Object.fromEntries(SCOPE_OPTIONS.map((s) => [s, 0]));
  records.forEach((r) => r.scope.forEach((s) => { counts[s] += 1; }));
  return SCOPE_OPTIONS.map((s) => counts[s]);
}

function scopeShareByNative(records) {
  const groups = { general: records.filter((r) => !r.bpmNative), native: records.filter((r) => r.bpmNative) };
  const result = {};
  for (const [key, group] of Object.entries(groups)) {
    const rated = ratedRecords(group);
    const denom = rated.length || 1;
    result[key] = SCOPE_OPTIONS.map((scope) => (rated.filter((r) => r.scope.includes(scope)).length / denom) * 100);
  }
  return result;
}

function genericShareBySource(records) {
  const yes = [];
  const no = [];
  ANALYSIS_SOURCE_ORDER.forEach((source) => {
    const rated = records.filter((r) => r.source === source && r.generic);
    const total = rated.length || 1;
    yes.push((rated.filter((r) => r.generic === "Yes").length / total) * 100);
    no.push((rated.filter((r) => r.generic === "No").length / total) * 100);
  });
  return { yes, no };
}

function lifecycleCounts(records) {
  const phases = [...LIFECYCLE_OPTIONS, "Not Applicable"];
  const counts = Object.fromEntries(phases.map((p) => [p, 0]));
  records.forEach((r) => r.lifecycle.forEach((p) => { counts[p] += 1; }));
  return { phases, counts: phases.map((p) => counts[p]) };
}

function meanRelevanceByScope(records) {
  return SCOPE_OPTIONS.map((scope) => {
    const withScope = records.filter((r) => r.scope.includes(scope));
    if (withScope.length === 0) return 0;
    return withScope.reduce((sum, r) => sum + r.relevance, 0) / withScope.length;
  });
}

/* ---- Page ---- */

function chartCard(title, description, canvasId, extra = []) {
  return el("div", { class: "chart-card" }, [
    el("h2", {}, title),
    description ? el("p", { class: "chart-desc" }, description) : null,
    el("div", { class: "chart-wrap" }, el("canvas", { id: canvasId })),
    ...extra,
  ]);
}

function legendDot(color, label) {
  return el("span", { class: "legend-item" }, [
    el("span", { class: "legend-dot", style: `background:${color}` }),
    el("span", {}, label),
  ]);
}

function buildAnalysisPage(records) {
  const pal = chartPalette();
  const totalRated = ratedRecords(records).length;

  const top20 = records
    .filter((r) => r.relevance !== null)
    .slice()
    .sort((a, b) => b.relevance - a.relevance)
    .slice(0, 20);

  const table = el("div", { class: "table-wrap" }, [
    el("table", { class: "data-table" }, [
      el("thead", {}, el("tr", {}, ["Source", "Guideline", "Relevance", "Scope", "Generic"].map((h) => el("th", {}, h)))),
      el("tbody", {}, top20.map((r) => el("tr", {}, [
        el("td", {}, SOURCE_SHORT_LABELS[r.source] || r.source),
        el("td", {}, r.name),
        el("td", {}, String(r.relevance)),
        el("td", {}, r.scope.join(", ")),
        el("td", {}, r.generic || ""),
      ]))),
    ]),
  ]);

  return el("div", { class: "card analysis-card" }, [
    el("div", { class: "btn-row btn-row-end" }, [
      el("a", { class: "ref-link", href: "analysis.json", download: "analysis.json" }, "Download full dataset (JSON) ↓"),
    ]),
    el("h1", {}, "How relevant is this guidance to BPM?"),
    el("p", { class: "intro-lead" },
      `An AI-generated first pass (Claude) rated all 425 guidelines across ${ANALYSIS_SOURCE_ORDER.length} sources ` +
      `for BPM relevance. ${totalRated} have a rating so far. Once real survey responses come in, this page is ` +
      "meant to show them here too, alongside this baseline."),

    el("div", { class: "analysis-grid" }, [
      chartCard("Guidelines collected per source", "How the 425 guidelines are distributed across sources.", "chart-per-source"),

      chartCard("BPM Relevance — overall", "0 = not relevant to BPM at all, 3 = highly relevant.", "chart-relevance-dist"),

      chartCard(
        "Share rated highly relevant, by source",
        "Percent of each source's guidelines scoring 3 (highly relevant).",
        "chart-high-relevance",
        [el("div", { class: "chart-legend" }, [legendDot(pal.muted, "General source"), legendDot(pal.strong, "BPM-native source")])]
      ),

      chartCard(
        "Relevance mix per source",
        "Full 0–3 breakdown per source, normalized to 100%.",
        "chart-relevance-mix",
        [el("div", { class: "chart-legend" }, RELEVANCE_OPTIONS.map((o, i) => legendDot(pal.relevanceSteps[i], o.label)))]
      ),

      chartCard("Which BPM layer do these guidelines touch?", "Count of guidelines acting on each layer (a guideline can touch more than one).", "chart-scope-counts"),

      chartCard(
        "BPM Scope emphasis — BPM-native vs. general sources",
        "Percent of each group's rated guidelines touching each layer.",
        "chart-scope-native",
        [el("div", { class: "chart-legend" }, [legendDot(pal.muted, "General source"), legendDot(pal.strong, "BPM-native source")])]
      ),

      chartCard(
        "Generic best practice vs. BPM-specific, by source",
        "Among rated guidelines: would the same advice apply outside BPM, or is the reasoning process-specific?",
        "chart-generic-share",
        [el("div", { class: "chart-legend" }, [legendDot(pal.muted, "Generic practice"), legendDot(pal.strong, "BPM-specific")])]
      ),

      chartCard("BPM Lifecycle phases touched", "Phase mentions across all guidelines (a guideline can span multiple phases).", "chart-lifecycle"),

      chartCard("Average relevance by BPM layer", "Mean BPM Relevance (0–3) among guidelines that touch each layer.", "chart-mean-by-scope"),
    ]),

    el("h2", { class: "top-table-heading" }, "Top-rated guidelines"),
    el("p", { class: "chart-desc" }, "The 20 highest-scoring guidelines across all sources."),
    table,
  ]);
}

function mountAnalysisCharts(records) {
  const pal = chartPalette();
  const shortLabels = ANALYSIS_SOURCE_ORDER.map((s) => SOURCE_SHORT_LABELS[s]);
  const legend = { display: false };
  const tooltip = baseTooltip(pal);

  mountChart("chart-per-source", {
    type: "bar",
    data: { labels: shortLabels, datasets: [{ data: countsPerSource(records), backgroundColor: pal.single, borderRadius: 4 }] },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip },
      scales: { x: baseScaleOptions(pal), y: { ...baseScaleOptions(pal), beginAtZero: true } },
    },
  });

  mountChart("chart-relevance-dist", {
    type: "bar",
    data: {
      labels: RELEVANCE_OPTIONS.map((o) => o.label),
      datasets: [{ data: relevanceDistribution(records), backgroundColor: pal.relevanceSteps, borderRadius: 4 }],
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip },
      scales: { x: baseScaleOptions(pal), y: { ...baseScaleOptions(pal), beginAtZero: true } },
    },
  });

  const nativeSet = new Set(["gbpp", "ppatterns", "lean"]);
  mountChart("chart-high-relevance", {
    type: "bar",
    data: {
      labels: shortLabels,
      datasets: [{
        data: highRelevanceShareBySource(records),
        backgroundColor: ANALYSIS_SOURCE_ORDER.map((s) => (nativeSet.has(s) ? pal.strong : pal.muted)),
        borderRadius: 4,
      }],
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip: { ...tooltip, callbacks: { label: (ctx) => `${ctx.parsed.y.toFixed(0)}%` } } },
      scales: { x: baseScaleOptions(pal), y: { ...baseScaleOptions(pal), beginAtZero: true, max: 100 } },
    },
  });

  const mixPerRelevance = relevanceDistributionPerSource(records);
  mountChart("chart-relevance-mix", {
    type: "bar",
    data: {
      labels: shortLabels,
      datasets: RELEVANCE_OPTIONS.map((o, i) => ({
        label: o.label, data: mixPerRelevance[i], backgroundColor: pal.relevanceSteps[i], stack: "mix",
      })),
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip: { ...tooltip, callbacks: { label: (ctx) => `${ctx.dataset.label}: ${ctx.parsed.y.toFixed(0)}%` } } },
      scales: {
        x: { ...baseScaleOptions(pal), stacked: true },
        y: { ...baseScaleOptions(pal), stacked: true, beginAtZero: true, max: 100 },
      },
    },
  });

  mountChart("chart-scope-counts", {
    type: "bar",
    data: { labels: SCOPE_OPTIONS, datasets: [{ data: scopeCounts(records), backgroundColor: pal.single, borderRadius: 4 }] },
    options: {
      indexAxis: "y",
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip },
      scales: { x: { ...baseScaleOptions(pal), beginAtZero: true }, y: baseScaleOptions(pal) },
    },
  });

  const scopeByNative = scopeShareByNative(records);
  mountChart("chart-scope-native", {
    type: "bar",
    data: {
      labels: SCOPE_OPTIONS,
      datasets: [
        { label: "General source", data: scopeByNative.general, backgroundColor: pal.muted, borderRadius: 3 },
        { label: "BPM-native source", data: scopeByNative.native, backgroundColor: pal.strong, borderRadius: 3 },
      ],
    },
    options: {
      indexAxis: "y",
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip: { ...tooltip, callbacks: { label: (ctx) => `${ctx.dataset.label}: ${ctx.parsed.x.toFixed(0)}%` } } },
      scales: { x: { ...baseScaleOptions(pal), beginAtZero: true, max: 100 }, y: baseScaleOptions(pal) },
    },
  });

  const genericShare = genericShareBySource(records);
  mountChart("chart-generic-share", {
    type: "bar",
    data: {
      labels: shortLabels,
      datasets: [
        { label: "Generic practice", data: genericShare.yes, backgroundColor: pal.muted, stack: "gen" },
        { label: "BPM-specific", data: genericShare.no, backgroundColor: pal.strong, stack: "gen" },
      ],
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip: { ...tooltip, callbacks: { label: (ctx) => `${ctx.dataset.label}: ${ctx.parsed.y.toFixed(0)}%` } } },
      scales: {
        x: { ...baseScaleOptions(pal), stacked: true },
        y: { ...baseScaleOptions(pal), stacked: true, beginAtZero: true, max: 100 },
      },
    },
  });

  const lc = lifecycleCounts(records);
  mountChart("chart-lifecycle", {
    type: "bar",
    data: { labels: lc.phases, datasets: [{ data: lc.counts, backgroundColor: pal.single, borderRadius: 4 }] },
    options: {
      indexAxis: "y",
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip },
      scales: { x: { ...baseScaleOptions(pal), beginAtZero: true }, y: baseScaleOptions(pal) },
    },
  });

  mountChart("chart-mean-by-scope", {
    type: "bar",
    data: { labels: SCOPE_OPTIONS, datasets: [{ data: meanRelevanceByScope(records), backgroundColor: pal.single, borderRadius: 4 }] },
    options: {
      indexAxis: "y",
      responsive: true, maintainAspectRatio: false,
      plugins: { legend, tooltip },
      scales: { x: { ...baseScaleOptions(pal), beginAtZero: true, max: 3 }, y: baseScaleOptions(pal) },
    },
  });
}

/* ---------- Boot ---------- */

async function boot() {
  renderApp(el("div", { class: "card" }, el("p", { class: "intro-lead" }, "Loading analysis…")));
  const res = await fetch("analysis.json");
  const records = await res.json();
  renderApp(buildAnalysisPage(records));
  mountAnalysisCharts(records);
}

boot();
